apiVersion: apps/v1
kind: Deployment
metadata:
  name: paytm-app
  labels:
    app: paytm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paytm
  template:
    metadata:
      labels:
        app: paytm
    spec:
      containers:
      - name: bus-container
        image: vedantrathi/bus
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: paytm-service
  labels:
    app: paytm
spec:
  selector:
    app: paytm
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

